package com.thriftyApp;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import androidx.test.core.app.ApplicationProvider;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

/**
 * Exercises {@link DatabaseHelper} against Robolectric's in-memory SQLite so
 * every CRUD path, query branch and the JSON backup/restore round-trip is
 * covered with real database behaviour rather than mocks.
 */
@RunWith(RobolectricTestRunner.class)
@Config(application = ThriftyApp.class)
public class DatabaseHelperTest {

    private DatabaseHelper helper;

    private static Contact contact(int budget) {
        Contact c = new Contact();
        c.setName("Ada");
        c.setEmailId("ada@example.com");
        c.setMobile(5550000L);
        c.setBudget(budget);
        c.setPassword("pw");
        return c;
    }

    private void insertTransactionRow(int uid, String tag, int exin, int amount, String when) {
        SQLiteDatabase db = helper.getWritableDatabase();
        ContentValues v = new ContentValues();
        v.put("uid", uid);
        v.put("tag", tag);
        v.put("exin", exin);
        v.put("amount", amount);
        v.put("created_at", when);
        db.insert("transactions", null, v);
        db.close();
    }

    @Before
    public void setUp() {
        helper = new DatabaseHelper(ApplicationProvider.getApplicationContext());
        // Force schema creation and start from a clean slate every test.
        SQLiteDatabase db = helper.getWritableDatabase();
        db.delete("contacts", null, null);
        db.delete("transactions", null, null);
        db.delete("alerts_table", null, null);
        db.close();
        Utils.userId = "1";
        Utils.income = 0;
        Utils.expense = 0;
    }

    @Test
    public void insertAndFetchUserByGoogleId() {
        helper.insertContact(contact(1000), "google-123");

        Contact found = helper.getUserByGoogleId("google-123");
        assertEquals("ada@example.com", found.getEmailId());
        assertEquals("Ada", found.getName());
        assertEquals(1000L, found.getBudget());

        Contact missing = helper.getUserByGoogleId("nope");
        assertNull(missing.getEmailId());
    }

    @Test
    public void searchUserIdReturnsRowThenEmptyWhenAbsent() {
        helper.insertContact(contact(2000), "g");
        // Discover the autogenerated id.
        Contact stored = helper.getUserByGoogleId("g");
        Utils.userId = String.valueOf(stored.getId());

        List<String> hit = helper.searchUserId(String.valueOf(stored.getId()));
        assertEquals(3, hit.size());
        assertEquals("2000", hit.get(2));

        List<String> miss = helper.searchUserId("999999");
        assertTrue(miss.isEmpty());
    }

    @Test
    public void searchPassMatchesByEmailAndFallsBackWhenNoMatch() {
        helper.insertContact(contact(1500), "g");

        List<String> match = helper.searchPass("ada@example.com");
        assertEquals("pw", match.get(0));

        List<String> noMatch = helper.searchPass("someone@else.com");
        assertEquals("Not Found", noMatch.get(0));
    }

    @Test
    public void searchPassOnEmptyTableReturnsEmptyList() {
        assertTrue(helper.searchPass("ada@example.com").isEmpty());
    }

    @Test
    public void getUserReadsCurrentUtilsUser() {
        helper.insertContact(contact(800), "g");
        Contact stored = helper.getUserByGoogleId("g");
        Utils.userId = String.valueOf(stored.getId());

        Contact u = helper.getUser();
        assertEquals("Ada", u.getName());
        assertEquals(800L, u.getBudget());
    }

    @Test
    public void changeBudgetPersistsNewValue() {
        helper.insertContact(contact(800), "g");
        Contact stored = helper.getUserByGoogleId("g");
        Utils.userId = String.valueOf(stored.getId());

        Utils.budget = "4242";
        helper.changeBudget();

        assertEquals(4242L, helper.getUser().getBudget());
    }

    @Test
    public void insertTransactionAndGetTransactionsFormatsIncomeAndExpense() {
        Transactions income = new Transactions();
        income.setUid(1);
        income.setTag("Salary");
        income.setExin(1);
        income.setAmount(500);
        helper.insertTransaction(income);

        // Expense row with a fixed timestamp covers the date-parsing branch.
        insertTransactionRow(1, "Food", 0, 30, "2026-05-01 12:00:00");
        // Row with an unparseable timestamp covers the parse-failure branch.
        insertTransactionRow(1, "Misc", 0, 5, "not-a-date");

        ArrayList<String> rows = helper.getTransactions();
        assertEquals(3, rows.size());
        boolean sawExpense = false;
        boolean sawIncome = false;
        for (String row : rows) {
            if (row.contains("- €")) {
                sawExpense = true;
            }
            if (row.contains("Salary")) {
                sawIncome = true;
            }
        }
        assertTrue(sawExpense);
        assertTrue(sawIncome);
    }

    @Test
    public void getTransactionsEmptyWhenNone() {
        assertTrue(helper.getTransactions().isEmpty());
    }

    @Test
    public void getTransactionsPdfWithAndWithoutDateRange() {
        insertTransactionRow(1, "Food", 0, 30, "2026-05-01 12:00:00");
        insertTransactionRow(1, "Rent", 0, 900, "2026-04-01 12:00:00");

        ArrayList<Transactions> all = helper.getTransactionsPDF(null, null);
        assertEquals(2, all.size());

        ArrayList<Transactions> filtered =
                helper.getTransactionsPDF("2026-04-30 00:00:00", "2026-05-31 00:00:00");
        assertEquals(1, filtered.size());
        assertEquals("Food", filtered.get(0).getTag());
    }

    @Test
    public void setIncomeExpensesAggregatesWithAndWithoutDates() {
        insertTransactionRow(1, "Salary", 1, 1000, "2026-05-01 12:00:00");
        insertTransactionRow(1, "Food", 0, 200, "2026-05-02 12:00:00");

        helper.setIncomeExpenses(null, null);
        assertEquals(1000, Utils.income);
        assertEquals(200, Utils.expense);

        helper.setIncomeExpenses("2026-05-01 00:00:00", "2026-05-01 23:59:59");
        assertEquals(1000, Utils.income);
        assertEquals(0, Utils.expense);
    }

    @Test
    public void getExpensesAndIncomesGroupByTag() {
        insertTransactionRow(1, "Food", 0, 50, "2026-05-01 12:00:00");
        insertTransactionRow(1, "Food", 0, 70, "2026-05-02 12:00:00");
        insertTransactionRow(1, "Salary", 1, 900, "2026-05-03 12:00:00");

        HashMap<String, Integer> expenses = helper.getExpenses(null, null);
        assertEquals(Integer.valueOf(120), expenses.get("Food"));

        HashMap<String, Integer> incomes =
                helper.getIncomes("2026-05-01 00:00:00", "2026-05-31 00:00:00");
        assertEquals(Integer.valueOf(900), incomes.get("Salary"));
    }

    @Test
    public void getDistinctTransactionMonths() {
        insertTransactionRow(1, "Food", 0, 10, "2026-05-01 12:00:00");
        insertTransactionRow(1, "Food", 0, 10, "2026-04-01 12:00:00");

        List<String> months = helper.getDistinctTransactionMonths();
        assertEquals(2, months.size());
        assertEquals("2026-05", months.get(0));
    }

    @Test
    public void reminderCrudLifecycle() {
        AlertsTable a = new AlertsTable();
        a.setUid(1);
        a.setMessage("Pay rent");
        a.setalert_at("2999-01-01 09:00:00");
        long id = helper.insertRemainder(a);
        assertTrue(id > 0);

        ArrayList<AlertsTable> future = helper.getReminders();
        assertEquals(1, future.size());

        AlertsTable byId = helper.getReminderById((int) id);
        assertNotNull(byId);
        assertEquals("Pay rent", byId.getMessage());

        byId.setMessage("Pay mortgage");
        byId.setalert_at("2999-02-01 09:00:00");
        assertEquals(1, helper.updateReminder(byId));
        assertEquals("Pay mortgage", helper.getReminderById((int) id).getMessage());

        helper.deleteReminder((int) id);
        assertNull(helper.getReminderById((int) id));
    }

    @Test
    public void getReminderByIdReturnsNullWhenMissing() {
        assertNull(helper.getReminderById(12345));
    }

    @Test
    public void deleteAndUpdateTransaction() {
        Transactions t = new Transactions();
        t.setUid(1);
        t.setTag("Food");
        t.setExin(0);
        t.setAmount(40);
        helper.insertTransaction(t);

        ArrayList<Transactions> rows = helper.getTransactionsPDF(null, null);
        assertEquals(1, rows.size());
        int tid = rows.get(0).getTid();

        Transactions edit = new Transactions();
        edit.setTid(tid);
        edit.setTag("Groceries");
        edit.setExin(0);
        edit.setAmount(45);
        helper.updateTransaction(edit);
        assertEquals("Groceries", helper.getTransactionsPDF(null, null).get(0).getTag());

        helper.deleteTransaction(tid);
        assertTrue(helper.getTransactionsPDF(null, null).isEmpty());
    }

    @Test
    public void exportAndImportBackupRoundTrip() {
        helper.insertContact(contact(1200), "g-1");
        insertTransactionRow(1, "Food", 0, 80, "2026-05-01 12:00:00");
        AlertsTable a = new AlertsTable();
        a.setUid(1);
        a.setMessage("Reminder");
        a.setalert_at("2999-01-01 09:00:00");
        helper.insertRemainder(a);

        String json = helper.exportBackup();
        assertTrue(json.contains("contacts"));
        assertTrue(json.contains("transactions"));
        assertTrue(json.contains("alerts"));

        // Wipe then restore from the JSON snapshot.
        SQLiteDatabase db = helper.getWritableDatabase();
        db.delete("contacts", null, null);
        db.delete("transactions", null, null);
        db.delete("alerts_table", null, null);
        db.close();

        helper.importBackup(json);
        assertEquals("ada@example.com", helper.getUserByGoogleId("g-1").getEmailId());
        assertEquals(1, helper.getTransactionsPDF(null, null).size());
        assertEquals(1, helper.getReminders().size());
    }

    @Test
    public void exportBackupOnEmptyDatabaseStillProducesJson() {
        String json = helper.exportBackup();
        assertTrue(json.startsWith("{"));
    }

    @Test
    public void importBackupWithInvalidJsonIsHandledGracefully() {
        helper.importBackup("not json");
        // No exception escapes; database remains usable.
        assertTrue(helper.getTransactionsPDF(null, null).isEmpty());
    }

    @Test
    public void onUpgradeRecreatesSchema() {
        SQLiteDatabase db = helper.getWritableDatabase();
        helper.onUpgrade(db, 1, 2);
        // Schema is intact: an insert/select succeeds after upgrade.
        helper.insertContact(contact(100), "g-upgrade");
        assertEquals("Ada", helper.getUserByGoogleId("g-upgrade").getName());
        db.close();
    }
}
